export const REGISTER_START_FETCHING = 'REGISTER_START_FETCHING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_START_FETCHING = 'LOGIN_START_FETCHING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT'

export const RESET_PASSWORD_SEND_EMAIL_START_FETCHING = 'RESET_PASSWORD_SEND_EMAIL_START_FETCHING' 
export const RESET_PASSWORD_SEND_EMAIL_SUCCESS = 'RESET_PASSWORD_SEND_EMAIL_SUCCESS'
export const RESET_PASSWORD_SEND_EMAIL_FAIL = 'RESET_PASSWORD_SEND_EMAIL_FAIL'

export const RESET_PASSWORD_START_FETCHING = 'RESET_PASSWORD_START_FETCHING' 
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'

export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS';
export const CHECK_TOKEN_FAIL = 'CHECK_TOKEN_FAIL';

export const SAVE_PROPOSAL_START_FETCHING = 'SAVE_PROPOSAL_START_FETCHING'
export const SAVE_PROPOSAL_SUCCESS = 'SAVE_PROPOSAL_SUCCESS'
export const SAVE_PROPOSAL_FAIL = 'SAVE_PROPOSAL_FAIL'

export const SAVE_DEMAND_START_FETCHING = 'SAVE_DEMAND_START_FETCHING'
export const SAVE_DEMAND_SUCCESS = 'SAVE_DEMAND_SUCCESS'
export const SAVE_DEMAND_FAIL = 'SAVE_DEMAND_FAIL'

export const GET_PROPSALS_START_FETCHING = 'GET_PROPSALS_START_FETCHING'
export const GET_PROPOSALS_SUCCESS = 'GET_PROPOSALS_SUCCESS'
export const GET_PROPOSALS_FAIL = 'GET_PROPOSALS_FAIL'

export const GET_PROPSALS_BY_ID_START_FETCHING = 'GET_PROPSALS_BY_ID_START_FETCHING'
export const GET_PROPOSALS_BY_ID_SUCCESS = 'GET_PROPOSALS_BY_ID_SUCCESS'
export const GET_PROPOSALS_BY_ID_FAIL = 'GET_PROPOSALS_BY_ID_FAIL'

export const GET_DEMANDS_START_FETCHING = 'GET_DEMANDS_START_FETCHING'
export const GET_DEMANDS_SUCCESS = 'GET_DEMANDS_SUCCESS'
export const GET_DEMANDS_FAIL = 'GET_DEMANDS_FAIL'

export const GET_DEMANDS_BY_ID_START_FETCHING = 'GET_DEMANDS_BY_ID_START_FETCHING'
export const GET_DEMANDS_BY_ID_SUCCESS = 'GET_DEMANDS_BY_ID_SUCCESS'
export const GET_DEMANDS_BY_ID_FAIL = 'GET_DEMANDS_BY_ID_FAIL'

export const GET_SUM_OF_SUCCESS = 'GET_SUM_OF_SUCCESS'
export const GET_SUM_OF_FAIL = 'GET_SUM_OF_FAIL'

export const DELETE_DEMAND_SUCCESS = 'DELETE_DEMAND_SUCCESS'
export const DELETE_DEMAND_FAIL = 'DELETE_DEMAND_FAIL' 

export const DELETE_PROPOSAL_SUCCESS = 'DELETE_PROPOSAL_SUCCESS'
export const DELETE_PROPOSAL_FAIL = 'DELETE_PROPOSAL_FAIL' 

export const EDIT_DEMAND_START_FETCHING = 'EDIT_DEMAND_START_FETCHING'
export const EDIT_DEMAND_SUCCESS = 'EDIT_DEMAND_SUCCESS'
export const EDIT_DEMAND_FAIL = 'EDIT_DEMAND_FAIL'

export const EDIT_PROPOSAL_START_FETCHING = 'EDIT_PROPOSAL_START_FETCHING'
export const EDIT_PROPOSAL_SUCCESS = 'EDIT_PROPOSAL_SUCCESS'
export const EDIT_PROPOSAL_FAIL = 'EDIT_PROPOSAL_FAIL'

export const CHANGE_PERSONAL_INFO_START_FETCHING = 'CHANGE_PERSONAL_INFO_START_FETCHING'
export const CHANGE_PERSONAL_INFO_SUCCESS = 'CHANGE_PERSONAL_INFO_SUCCESS'
export const CHANGE_PERSONAL_INFO_FAIL = 'CHANGE_PERSONAL_INFO_FAIL'

export const UPDATE_PASSWORD_START_FETCHING = 'UPDATE_PASSWORD_START_FETCHING'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'

export const REGION_FILTERS_SUM_OF = 'REGION_FILTERS_SUM_OF'
export const CITY_FILTERS_SUM_OF = 'CITY_FILTERS_SUM_OF'
export const TYPE_FILTERS_SUM_OF = 'TYPE_FILTERS_SUM_OF'

export const ADD_ERRORS = 'ADD_ERRORS'
export const DELETE_ERRORS = 'DELETE_ERRORS'