const initialState = {
    common: {
        proposal: "",
        demand: "",
        region: "",
        city: "",
        type: "",
        subType: "",
        price: "",
        unit: "",
        available_quantity: "",
        email: "",
        phone: "",
        description_one_word: "",
        comment: "",
        plan_to_have: "",
        quantity: "",
        when: "",
        add: "",
        oneTime: "",
        continuous: "",
        frequency: "",
        year: "",
        month: "",
        day: "",
        week: "",
        mark_the_date: "",
        username: "",
        password: "",
        repeat_password: "",
        yourName: "",
        current_password: "",
        new_password: "",
        repeat_new_password: "",
        more: "",
        login: "",
        register: "",
        send_instruction: "",
        change_password: "",
        ask_to_delete: "",
        delete: "",
        cancel: ""
    },
    Login: {
        forgot_password: ""
    },
    Register: {
        registrationSuccess: ""
    },
    addNewDemand: {
    },
    Navigation: {
        login: "",
        register: "",
        addNewProposal: "",
        addNewDemand: "",
        my_statements: "",
        settings: "",
        logout: ""
    },
    Settings: {
        change_personal_info: "",
        change_password: "",
        remove_account: ""
    },
    Filter: {
        regions: {
            erevan: "",
            aragacotn: "",
            ararat: "",
            armavir: "",
            gexarkunik: "",
            kotayk: "",
            lori: "",
            shirak: "",
            syunik: "",
            tavush: "",
            vayoc_cor: ""
        },
        cities: {
            erevan: "",
            ashtarak: "",
            aparan: "",
            talin: "",
            ararat: "",
            artashat: "",
            masis: "",
            vedi: "",
            armavir: "",
            vaxarshapat: "",
            mecamor: "",
            gavar: "",
            jambarak: "",
            martuni: "",
            sevan: "",
            vardenis: "",
            abovyan: "",
            byurexavan: "",
            exvard: "",
            nor_hajn: "",
            charencavan: "",
            alaverdi: "",
            axtala: "",
            tumanyan: "",
            shamlux: "",
            spitak: "",
            stepanavan: "",
            tashir: "",
            artik: "",
            gyumri: "",
            maralik: "",
            agarak: "",
            goris: "",
            dastakert: "",
            kapan: "",
            mexri: "",
            sisian: "",
            qajaran: "",
            ayrum: "",
            berd: "",
            dilijan: "",
            ijevan: "",
            noyemberyan: "",
            exegnacor: "",
            jermuk: "",
            vayq: ""
        },
        types: {
            katnamterq: "",
            msamterq: "",
            kendaniner: "",
            trchunner_cu: "",
            ckner_ikra: "",
            mexvamterq: "",
            banjarexen: "",
            mirg: "",
            hataptux: "",
            ynkuzexen: "",
            grain_culture: "",
            chir_ev_charaz: "",
            pahaconer: "",
            kanachexen: "",
            busakan_teyer: "",
            tnkiner: ""
        },
        subTypes: {
            panir: "",
            kat: "",
            macun: "",
            katnashor: "",
            karag: "",
            yux: "",
            garan_mis: "",
            khozi_mis: "",
            tavari_mis: "",
            jagari_mis: "",
            havi_mis: "",
            aqlori_mis: "",
            jagar: "",
            kov: "",
            hort: "",
            vochxar: "",
            gar: "",
            khoz: "",
            khochkor: "",
            cu: "",
            ikra: "",
            mexr: "",
            mexvamom: "",
            propolis: "",
            mexvayntaniq: "",
            mexvamayr: "",
            petak: "",
            caxkaposhi: "",
            varung: "",
            pomidor: "",
            kartofil: "",
            kaxamb: "",
            sxtor: "",
            badrijan: "",
            khncor: "",
            tanc: "",
            ciran: "",
            nur: "",
            tuz: "",
            dzmeruk: "",
            limon: "",
            khaxox: "",
            mori: "",
            malina: "",
            haxarj: "",
            aloj: "",
            mosh: "",
            hon: "",
            coren: "",
            gari: "",
            kukuruz: "",
            grechka: "",
            hajar: "",
            chamich: "",
            cirani_chir: "",
            salori_chir: "",
            chor_tut: "",
            cirani_jem: "",
            khncor_jem: "",
            hamem: "",
            petrushka: "",
            rehan: "",
            aveluk: "",
            nana: "",
            urc: "",
            mrgatu_careri: "",
            hataptxayin_tperi: "",
            banjarexenayin_buyseri: ""
        },
        units: {
            kg: "",
            hat: "",
            litr: "",
            metr: "",
            tonna: "",
            centner: "",
            gram: "",
            punj: ""
        }
    },
    warningMsgs: {
        not_empty_not_correct: "",
        not_correct: "",
        not_empty_min_3: "",
        min_3: "",
        not_empty_min_7: "",
        min_7: "",
        passwords_not_match: "",
        from_list: "",
        not_empty: "",
        email_or_phone_not_empty: "",
        should_be_one_word: "",
        should_not_be_more_25: ""
    },
    serverErrMsgs: {
        bad_email_or_password: "",
        email_not_correct: "",
        username_not_correct: "",
        password_not_correct: "",
        passwords_not_matched: "",
        something_wrong: "",
        email_not_found: "",
        wrong_current_password: ""
    }
}

const content = (state = initialState, action) => {
    switch (action.type) {
        case 'SET_LANG':
            return {
                ...state,
                ...action.payload
            }    
        default:
            return state
    }
}

export default content;